name: FragMAXPrep
channels:
  - conda-forge
dependencies:
  - python=3.9.6
  - voila=0.2.10
  - jupyterlab=3.1.0
  - ipywidgets=7.6.3
  - pandas=1.3.1
  - sqlalchemy=1.4.22
  - matplotlib=3.4.2
  - qgrid=1.3.1
  - beakerx=1.4.1
